import React, { useState } from "react";
import { RiCloseLine } from "react-icons/ri";
import styles from "./Modal.module.css";
import ReceiptDrawer from "./receipt";

const SeatDrawer = ({ drawerIsOpen, item }) => {
  const [person, setPerson] = useState([]);
  const [total, setTotal] = useState([]);
  const [openReceipt, receiptIsOpen] = useState(false);
  const result = total.length * item.fare;

  const handleChange = (e) => {
    if (e.target.checked === true) {
      setPerson((prev) => [...prev, e.target.name, ",   "]);
      setTotal((prev) => [...prev, e.target.value]);
    } else {
      setPerson((prev) => []);
      setTotal((prev) => []);
    }
  };
  return (
    <React.Fragment>
      <div className={styles.modal} key={item?.id}>
        <div className={styles.modalHeader}>
          <div>
            <button
              className={styles.closeBtn}
              onClick={() => drawerIsOpen(false)}
            >
              <RiCloseLine style={{ marginBottom: "-3px" }} />
            </button>
          </div>
        </div>
        <div className="col">
          <div className={styles.front}>
            <h5>FRONT</h5>
          </div>
        </div>
        <div className="col">
          <div className="row-sm">
            <form action="#" className={styles.seatrow}>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS1"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS3"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS5"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS7"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS9"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS11"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS13"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS15"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS17"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LWS19"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
            </form>
          </div>

          <div className="row-sm">
            <form action="#" className={styles.seatrow}>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS2"
                    value={item.fare}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS4"
                    value={item.id}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS6"
                    value="id3"
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS8"
                    value="id3"
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS10"
                    value="id3"
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS12"
                    value={item.id}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS14"
                    value={item.id}
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS16"
                    value="id3"
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS18"
                    value="id3"
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
              <p>
                <label>
                  <input
                    type="checkbox"
                    name="LS20"
                    value="id3"
                    onChange={handleChange}
                  />
                  <span></span>
                </label>
              </p>
            </form>
          </div>
          <div className={styles.single}>
            <div className="row-sm">
              <form action="#" className={styles.seatrow}>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS1"
                      value={item.id}
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS3"
                      value={item.id}
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS5"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS7"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS9"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS11"
                      value={item.id}
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS13"
                      value={item.id}
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS15"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS17"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RS19"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
              </form>
            </div>

            <div className="row-sm">
              <form action="#" className={styles.seatrow}>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS2"
                      value={item.id}
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS4"
                      value={item.id}
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS6"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS8"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS10"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS12"
                      value={item.id}
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS14"
                      value={item.id}
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS16"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS18"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
                <p>
                  <label>
                    <input
                      type="checkbox"
                      name="RWS20"
                      value="id3"
                      onChange={handleChange}
                    />
                    <span></span>
                  </label>
                </p>
              </form>
            </div>
          </div>
        </div>
        <div>
          <div className="col">
            <p>
              <label>
                <input
                  type="checkbox"
                  name="BS1"
                  value={item.id}
                  onChange={handleChange}
                />
                <span></span>
              </label>
            </p>
            <p>
              <label>
                <input
                  type="checkbox"
                  name="BS2"
                  value={item.id}
                  onChange={handleChange}
                />
                <span></span>
              </label>
            </p>
            <p>
              <label>
                <input
                  type="checkbox"
                  name="BS3"
                  value="id3"
                  onChange={handleChange}
                />
                <span></span>
              </label>
            </p>
            <p>
              <label>
                <input
                  type="checkbox"
                  name="BS4"
                  value="id3"
                  onChange={handleChange}
                />
                <span></span>
              </label>
            </p>
            <p>
              <label>
                <input
                  type="checkbox"
                  name="BS5"
                  value="id3"
                  onChange={handleChange}
                />
                <span></span>
              </label>
            </p>
          </div>
        </div>

        <div className="col">
          <div className={styles.seatid}>
            <h6>Seat ID: {person}</h6>
          </div>
          <div className={styles.seatid}>
            <h5>Total: {result} Pesos</h5>
          </div>
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => receiptIsOpen(true)}
          >
            PROCEED TO BOOK
          </button>
        </div>
      </div>

      {openReceipt && (
        <ReceiptDrawer openReceipt={openReceipt} key={item?.id} item={item} result={result} person={person}/>
      )}
    </React.Fragment>
  );
};

export default SeatDrawer;
